### ISSUE TITLE
Not able to run as Non-root user

### ISSUE THREAD

**Issue by yomiso** [Depau/fastgate-python#1]
Hi, I am a user with limited privilege on the machine and I can't install python packages. Is there a way to run `fastgate-python` without installing it? (a standlone script would be nice)

**Comment by depau** [comment]
Either use a [virtualenv](https://docs.python.org/3/library/venv.html) or install the dependencies manually system-wide (`requests` and `Click`) and run `python3 -m fastgate` in the project directory (where the `fastgate` package is located).

You can find instructions online on how to create a virtualenv without having the `virtualenv` or `venv` module installed.
